### PR TITLE
Gem update for rack-protection

### PR DESCRIPTION
**Pull request by werebus**
Also, Girl -> Bot, and updated the database.yml.example to have a test db.

### CODE REVIEW

**Comment by greysteil** [comment]
Would you be up for using [Dependabot](https://dependabot.com) to keep the dependencies on this repo up-to-date? I've spent the last year building it and hopefully it could save you some time. It's totally free for open source and always will be - I'm just trying to get more people using it.

**Comment by Anbranin** [comment]
@greysteil I visited your page, it looks amazing, we'll definitely look into it. One small comment: Your paragraph here:
>You check your tests pass, scan the included changelog and release notes, then hit merge with confidence.
is missing either a conditional or the word "that" after "You check", as in "You check that your tests pass" or "you check if your tests pass" (I like *that* better).

**Comment by greysteil** [comment]
Awesome, thanks @Anbranin - updated!

**Comment by werebus** [comment]
This PR _does_ delete that file. Or do I misunderstand you?

**Comment by mboneil10** [comment]
OMG SORRY

**Pull request merged**
